import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  auditProcessSidebar:       [{type: 'autogenerated', dirName: '01-audit-process'}],
  itGovernanceSidebar:       [{type: 'autogenerated', dirName: '02-it-governance'}],
  systemDevelopmentSidebar:  [{type: 'autogenerated', dirName: '03-system-development'}],
  itOperationsSidebar:       [{type: 'autogenerated', dirName: '04-it-operations'}],
  informationSecuritySidebar:[{type: 'autogenerated', dirName: '05-information-security'}],
  auditToolkitsSidebar:      [{type: 'autogenerated', dirName: '06-audit-toolkits'}],
};

export default sidebars;
